### ISSUE TITLE
.range(..., count_only=True) returns a count of None if no matching keys found; should be 0

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#74]
### Description

Currently if `count_only` is set and handed to `client.range()` and no keys are found, the `result.count` is `None`.  
### What I Did

This leads to a bunch of extra checking that looks like:
```
found = cilent.range(key, count_only=True).count
if found is None: 
    found = 0
if found > 3:
   ...
```

### What I Expected

I expected that a `count` should always be an `int`.  Having to put in a bunch of 'is this ~~null~~None?` checks is unbeautiful to say the least.  Could you put the _one_ check in the right place (at deserialization/result-object-creation time)?

**Comment by Revolution1** [comment]
you are right.

https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/etcdserver/etcdserverpb/rpc.pb.go#L442-L447

the go client will `return 0` instead of a `nil`.

I planned to implement some higher level api like `get(key)` `all()` `count(key)` `exists(key)` etc.

`range` is too low level and kind of unfriendly.

And I can modify the model to set number-type value to 0 when it is None

**Comment by Revolution1** [comment]
I will publish a new release in a few days
