### ISSUE TITLE
Counting keys in a transaction compare?

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#76]
Is there a way to do a comparison on the count of keys with a prefix inside a transaction? That is, I want to do something like:

    txn.compare( txn.key('/prefix/', count_only=True).value < 10)

To only allow the txn.success() bit to run if there are less than ten items with the prefix /prefix/. I believe the go client can do this using WithPrefix() and CountOnly() but I can't find where/if something similar is available here.

**Comment by Revolution1** [comment]
Go client can not do it either.

https://github.com/etcd-io/etcd/blob/v3.3.12/clientv3/compare.go#L110-L120
https://github.com/etcd-io/etcd/blob/v3.3.12/etcdserver/etcdserverpb/rpc.proto#L528-L540
https://github.com/etcd-io/etcd/blob/master/etcdserver/apply.go#L464-L506

You can only compare version, create_revision, mod_revision, value, lease_id of a key.
And you can provide a range_end to compare a range of key at the same time.

But no "count" supported, you can not use `CountOnly()` here.

So if you want that feature, you can fire a issue at https://github.com/etcd-io/etcd

And, there is no low-cost way to maintain a counter since etcd3 has no atomic incr and decr.

> ps: etcd3-py missed the lease_id and range_end, will implement it later.

**Comment by pjz** [comment]
I *think* that https://github.com/etcd-io/etcd/issues/8241 says that this can be done somehow using WithPrefix() and Version?  But I don't really understand.  Does that post (or the code it points to) make sense to you?

**Comment by Revolution1** [comment]
The use of txn here: 

https://github.com/heyitsanthony/scraps/blob/34f2fb985eebe9a8d6fff39064c56eb7580f3721/delkeypfx/main.go#L23

is a special case:

when you compare a range's version to a integer, etcd will find all kvs within the range, and compare their verision one by one.

when there is no key that satisfy that range, these code will run:

https://github.com/etcd-io/etcd/blob/a621d807f061e1dd635033a8d6bc261461429e27/etcdserver/apply.go#L454

etcd server will compare the target version number with a empty kv struct which Version is the default value of go int: `0`. (A existing kv always has a non zero version)

so `txn.compare(txn.key('prefix', prefix=True).version == 0)` means "there is no key that has this prefix"

Accidentally it's the same as `txn.compare(txn.key('prefix', count=True) == N)` . Unfortunately, `N` can only be `0`, and there is no such compare target "`count`".

Now you may know why `txn.compare( txn.key('/prefix/', count_only=True).value < 10)` is not possible in etcd3

**Comment by pjz** [comment]
Ahh, thanks for the explanation.  I've opened a ticket with the feature request ( https://github.com/etcd-io/etcd/issues/10607 ) but I won't hold my breath.

**Comment by Revolution1** [comment]
Yea. I think `prefix.version == 0` is kinda like a undefined behavior.
etcd could do better in txn feature.
